language: ruby
sudo: false
cache: bundler
bundler_args: --without guard
script: "bundle exec rspec"
rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1
env:
  - "RAILS_VERSION=6.0"
  - "RAILS_VERSION=5.2"
  - "RAILS_VERSION=5.1"
  - "RAILS_VERSION=5.0"
  - "RAILS_VERSION=4.2"
  
